# Generated by Django 4.1.7 on 2023-05-03 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackendAPI', '0003_alter_facturas_capital_alter_facturas_cuotas_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clientes',
            new_name='Cliente',
        ),
        migrations.RenameModel(
            old_name='Facturas',
            new_name='Factura',
        ),
        migrations.RenameModel(
            old_name='HistorialFacturas',
            new_name='HistorialFactura',
        ),
    ]
